# Generated by Django 3.0.4 on 2020-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('task_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Task_id')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'scheduledReports',
            },
        ),
    ]
